{
  "sksl": {
    "entrypoint": "absorption_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 u_resolution;\nuniform vec2 u_target;\nuniform float u_time;\nuniform shader u_texture;\nuniform half2 u_texture_size;\n\nvec4 fragColor;\n\nvoid FLT_main()\n{\n    vec2 uv = flutter_FragCoord.xy / u_resolution;\n    float progress = clamp(u_time, 0.0, 1.0);\n    vec2 delta = uv - u_target;\n    vec2 stretchedDelta = vec2(delta.x * (1.0 + (0.5 * progress)), delta.y);\n    vec2 newDelta = stretchedDelta * (1.0 - progress);\n    vec2 newUV = u_target + newDelta;\n    newUV = clamp(newUV, vec2(0.0), vec2(1.0));\n    fragColor = u_texture.eval(u_texture_size * ( newUV));\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 0,
        "name": "u_texture",
        "rows": 1,
        "type": 12
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "u_resolution",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "u_target",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "u_time",
        "rows": 1,
        "type": 10
      }
    ]
  }
}