{
  "sksl": {
    "entrypoint": "black_hole_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 u_resolution;\nuniform vec2 u_blackHoleCenter;\nuniform float u_time;\nuniform shader u_texture;\nuniform half2 u_texture_size;\n\nvec4 fragColor;\n\nvoid FLT_main()\n{\n    vec2 uv = flutter_FragCoord.xy / u_resolution;\n    vec2 delta = uv - u_blackHoleCenter;\n    float dist = length(delta);\n    float swirl = (0.5 * exp((-dist) * 10.0)) * u_time;\n    float angle = atan(delta.y, delta.x) + swirl;\n    float radius = dist - ((0.300000011920928955078125 * exp((-dist) * 15.0)) * u_time);\n    vec2 distortedUV = u_blackHoleCenter + (vec2(cos(angle), sin(angle)) * radius);\n    distortedUV = clamp(distortedUV, vec2(0.0), vec2(1.0));\n    fragColor = u_texture.eval(u_texture_size * ( distortedUV));\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "u_resolution",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "u_blackHoleCenter",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "u_time",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 3,
        "name": "u_texture",
        "rows": 1,
        "type": 12
      }
    ]
  }
}