{
  "sksl": {
    "entrypoint": "pulse_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform float u_time;\n\nvec4 fragColor;\n\nvoid FLT_main()\n{\n    vec2 uv = flutter_FragCoord.xy / vec2(800.0, 600.0);\n    float r = 0.5 + (0.5 * sin(u_time));\n    float g = 0.5 + (0.5 * cos(u_time * 1.5));\n    float b = uv.x;\n    fragColor = vec4(r, g, b, 1.0);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "u_time",
        "rows": 1,
        "type": 10
      }
    ]
  }
}